version: '3.1'

services:
  cms:
    image: drupal:9
    ports:
      - '8080:80'
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      # this takes advantage of the feature in Docker that a new anonymous
      # volume (which is what we're creating here) will be initialized with the
      # existing content of the image at the same location
      - drupal-sites:/var/www/html/sites
    restart: always
  postgres-db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: examplepassword

# Establishing named volumes
volumes:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites:
